apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
    - name: web-monitor
      image: benjaminhck/sdu-cloud-frontend:v1
      imagePullPolicy: "Always"
      ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: svc-frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      name: web-monitor
      port: 8080
      targetPort: 80
